services:
  - type: web
    name: beyond-buttons
    runtime: node
    repo: https://github.com/vasimdevelops-collab/beyond-buttons
    plan: starter
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production